export const SET_ENTER_STATE = 'SET_ENTER_STATE'
export const RESET_ENTER_STATE = 'RESET_ENTER_STATE'
export const SET_VERIFICATION_STATE = 'SET_VERIFICATION_STATE'
export const SET_TRANSACTIONS_STATE = 'SET_TRANSACTIONS_STATE'
export const SET_BALANCE_STATE = 'SET_BALANCE_STATE'
export const SET_PROCESS_STATE = 'SET_PROCESS_STATE'
export const RESET_PROCESS_STATE = 'RESET_PROCESS_STATE'
export const SET_USERS_STATE = 'SET_USERS_STATE'
export const UPDATE_USER_STATUS = 'UPDATE_USER_STATUS'
export const SET_PASSPORT_STATE = 'SET_PASSPORT_STATE'

export default {
  SET_ENTER_STATE,
  RESET_ENTER_STATE,
  SET_VERIFICATION_STATE,
  SET_BALANCE_STATE,
  SET_TRANSACTIONS_STATE,
  SET_PASSPORT_STATE,
  SET_PROCESS_STATE,
  RESET_PROCESS_STATE,
  SET_USERS_STATE,
  UPDATE_USER_STATUS
}
